export const vocabularyList = () => {
  return [
    { en: 'spoon', th: 'ช้อน' },
    { en: 'knife', th: 'มีด' },
    { en: 'book', th: 'หนังสือ' },
    { en: 'pen', th: 'ปากกา' },
    { en: 'pencil', th: 'ดินสอ' },
    { en: 'bottle', th: 'ขวด' },
    { en: 'box', th: 'กล่อง' },
    { en: 'bag', th: 'ถุง' },
    { en: 'basket', th: 'ตะกร้า' },
    { en: 'rope', th: 'เชือก' },
    { en: 'chain', th: 'โซ่' },
    { en: 'keychain', th: 'พวงกุญแจ' },
    { en: 'card', th: 'การ์ด' },
    { en: 'letter', th: 'จดหมาย' },
    { en: 'envelope', th: 'ซองจดหมาย' },
    { en: 'stamp', th: 'แสตมป์' },
    { en: 'paper', th: 'กระดาษ' },
    { en: 'notebook', th: 'สมุด' },
    { en: 'diary', th: 'ไดอารี่' },
    { en: 'calendar', th: 'ปฏิทิน' },
    { en: 'clock', th: 'นาฬิกา' },
    { en: 'glove', th: 'ถุงมือ' },
    { en: 'helmet', th: 'หมวกกันน็อก' },
    { en: 'scarf', th: 'ผ้าพันคอ' },
    { en: 'belt', th: 'เข็มขัด' },
    { en: 'wallet', th: 'กระเป๋าสตางค์' },
    { en: 'purse', th: 'กระเป๋าถือ' },
    { en: 'suitcase', th: 'กระเป๋าเดินทาง' },
    { en: 'toothbrush', th: 'แปรงสีฟัน' },
    { en: 'toothpaste', th: 'ยาสีฟัน' },
    { en: 'comb', th: 'หวี' },
    { en: 'mirror', th: 'กระจก' },
    { en: 'razor', th: 'มีดโกน' },
    { en: 'tissue', th: 'กระดาษทิชชู' },
    { en: 'napkin', th: 'ผ้าเช็ดปาก' },
    { en: 'hairbrush', th: 'แปรงผม' },
    { en: 'clip', th: 'คลิป' },
    { en: 'pin', th: 'เข็มกลัด' },
    { en: 'rubber band', th: 'ยางรัด' },
    { en: 'glue', th: 'กาว' },
    { en: 'scissors', th: 'กรรไกร' },
    { en: 'ruler', th: 'ไม้บรรทัด' },
    { en: 'eraser', th: 'ยางลบ' },
    { en: 'sharpener', th: 'ที่เหลาดินสอ' },
    { en: 'marker', th: 'ปากกาเมจิก' },
    { en: 'chalk', th: 'ชอล์ก' },
    { en: 'paint', th: 'สี' },
    { en: 'brush', th: 'แปรง' },
    { en: 'canvas', th: 'ผ้าใบ' },
    { en: 'frame', th: 'กรอบ' },
    { en: 'photo', th: 'รูปถ่าย' },
    { en: 'camera', th: 'กล้องถ่ายรูป' },
    { en: 'lens', th: 'เลนส์' },
    { en: 'tripod', th: 'ขาตั้งกล้อง' },
    { en: 'microphone', th: 'ไมโครโฟน' },
    { en: 'speaker', th: 'ลำโพง' },
    { en: 'headphones', th: 'หูฟัง' },
    { en: 'keyboard', th: 'แป้นพิมพ์' },
    { en: 'mouse', th: 'เมาส์' },
    { en: 'screen', th: 'หน้าจอ' },
    { en: 'printer', th: 'เครื่องพิมพ์' },
    { en: 'scanner', th: 'เครื่องสแกน' },
    { en: 'USB', th: 'แฟลชไดรฟ์' },
    { en: 'charger', th: 'ที่ชาร์จ' },
    { en: 'battery', th: 'แบตเตอรี่' },
    { en: 'light bulb', th: 'หลอดไฟ' },
    { en: 'cable', th: 'สายเคเบิล' },
    { en: 'plug', th: 'ปลั๊ก' },
    { en: 'socket', th: 'เต้ารับ' },
    { en: 'heater', th: 'เครื่องทำความร้อน' },
    { en: 'air conditioner', th: 'เครื่องปรับอากาศ' },
    { en: 'washing machine', th: 'เครื่องซักผ้า' },
    { en: 'vacuum cleaner', th: 'เครื่องดูดฝุ่น' },
    { en: 'iron', th: 'เตารีด' },
    { en: 'cooking pot', th: 'หม้อ' },
    { en: 'pan', th: 'กระทะ' },
    { en: 'spatula', th: 'ตะหลิว' },
    { en: 'cutting board', th: 'เขียง' },
    { en: 'bowl', th: 'ชาม' },
    { en: 'mug', th: 'แก้วมัค' },
    { en: 'thermos', th: 'กระติกน้ำร้อน' },
    { en: 'strainer', th: 'ที่กรอง' },
    { en: 'ladle', th: 'ทัพพี' },
    { en: 'blender', th: 'เครื่องปั่น' },
    { en: 'toaster', th: 'เครื่องปิ้งขนมปัง' },
    { en: 'grill', th: 'เตาย่าง' },
    { en: 'microwave', th: 'ไมโครเวฟ' },
    { en: 'dishwasher', th: 'เครื่องล้างจาน' },
    { en: 'rice cooker', th: 'หม้อหุงข้าว' },
    { en: 'trash can', th: 'ถังขยะ' },
    { en: 'broom', th: 'ไม้กวาด' },
    { en: 'mop', th: 'ไม้ถูพื้น' },
    { en: 'bucket', th: 'ถังน้ำ' },
    { en: 'Initiative', th: 'ความคิดริเริ่ม' },
    { en: 'Effectiveness', th: 'ประสิทธิผล' },
    { en: 'Delegation', th: 'ตัวแทน' },
    { en: 'Expert', th: 'ผู้เชี่ยวชาญ' },
    { en: 'Tactic', th: 'ชั้นเชิง' },
    { en: 'Proposal', th: 'แผนงาน' },
    { en: 'Selection', th: 'การคัดเลือก' },
    { en: 'Praise', th: 'คำชม' },
    { en: 'Observation', th: 'การสังเกต' },
    { en: 'Workload', th: 'จำนวนงาน' },
    { en: 'Goods', th: 'สินค้า' },
    { en: 'Replacement', th: 'ทดแทน' },
    { en: 'Matter', th: 'ปัญหา, เหตุการณ์' },
    { en: 'Confirmation', th: 'การรับรอง' },
    { en: 'Figures', th: 'ตัวเลข' },
    { en: 'Requirement', th: 'ความประสงค์' },
    { en: 'Deadline', th: 'วันกำหนดส่งงาน' },
    { en: 'Opportunity', th: 'โอกาส' },
    { en: 'Objective', th: 'จุดประสงค์' },
    { en: 'Overview', th: 'ภาพรวม' },
    { en: 'Attention', th: 'ความสนใจ' },
    { en: 'Assumption', th: 'สมมติฐาน' },
    { en: 'Point', th: 'ข้อสำคัญ' },
    { en: 'Survey', th: 'แบบสอบถาม' },
    { en: 'Feature', th: 'ลักษณะโดดเด่น' },
    { en: 'Analysis', th: 'วิเคราะห์' },
    { en: 'Notice', th: 'แจ้งเตือน' },
    { en: 'Assign to', th: 'มอบหมายให้' },
    { en: 'Maximize', th: 'ขยายใหญ่สุด' },
    { en: 'Occupy', th: 'ครอบครอง' },
    { en: 'Compare', th: 'เปรียบเทียบ' },
    { en: 'Launch', th: 'เปิดตัว' },
    { en: 'Implement', th: 'นำมาใช้' },
    { en: 'Perceive', th: 'เข้าใจ, รับรู้' },
    { en: 'Receive', th: 'ได้รับ' },
    { en: 'Deserve', th: 'เหมาะสม' },
    { en: 'Admire', th: 'นับถือ' },
    { en: 'Pressure', th: 'กดดัน' },
    { en: 'Expect', th: 'คาดหวัง' },
    { en: 'Hinder', th: 'ขัดขวาง' },
    { en: 'Deliver', th: 'ส่ง' },
    { en: 'Update', th: 'ปรับปรุงให้ทันสมัย' },
    { en: 'Abandon', th: 'ละทิ้ง' },
    { en: 'Disapprove', th: 'ไม่ชอบ' },
    { en: 'Send', th: 'ออกคำสั่ง' },
    { en: 'Assent', th: 'ยินยอม' },
    { en: 'Estimate', th: 'ประมาณ' },
    { en: 'Assume', th: 'สันนิษฐาน' },
    { en: 'Demand', th: 'ต้องการ' },
    { en: 'Specific', th: 'เฉพาะเจาะจง' },
    { en: 'Attend', th: 'เข้าร่วม' },
    { en: 'Present', th: 'บรรยาย' },
    { en: 'Elaborate', th: 'ขยายความ' },
    { en: 'Require', th: 'ต้องการ' },
    { en: 'Inform', th: 'แจ้งให้ทราบ' },
    { en: 'Reasonable', th: 'มีเหตุผล' },
    { en: 'Effective', th: 'ประสิทธิภาพ' },
    { en: 'Face-to-face', th: 'เผชิญหน้ากัน' },
    { en: 'Troublesome', th: 'เป็นภาระ' },
    { en: 'Collaborative', th: 'ร่วมมือกัน' },
    { en: 'Groundbreaking', th: 'นวัตกรรมใหม่' },
    { en: 'Uninspired', th: 'ไม่น่าสนใจ' },
    { en: 'Productive', th: 'อย่างมีประสิทธิภาพ' },
    { en: 'Faulty', th: 'ผิดพลาด' },
    { en: 'Final', th: 'สุดท้าย' },
    { en: 'Urgent', th: 'ด่วน' },
    { en: 'Up-to-date', th: 'ทันสมัย' },
    { en: 'In particular', th: 'โดยเฉพาะอย่างยิ่ง' },
    { en: 'Extra', th: 'เพิ่ม, มากขึ้น' },
    { en: 'Formal', th: 'ทางการ' },
    { en: 'Informal', th: 'ไม่เป็นทางการ' },
    { en: 'Hectic', th: 'ยุ่ง' },
    { en: 'Genuine', th: 'แท้' },
    { en: 'Annual', th: 'ประจำปี' },
    { en: 'Essential', th: 'สำคัญ' },
    { en: 'Necessary', th: 'จำเป็น' },
    { en: 'Full-time', th: 'เต็มเวลา' },
    { en: 'Part-time', th: 'ไม่เต็มเวลา' },
    { en: 'Unique', th: 'แตกต่าง' },
    { en: 'Accessible', th: 'เข้าถึงได้' },
    { en: 'Flexible', th: 'ยืดหยุ่นได้' },
    { en: 'Properly', th: 'อย่างสมควร' },
    { en: 'Absolutely', th: 'อย่างแน่นอน' },
    { en: 'Unfortunately', th: 'น่าเสียดาย' },
    { en: 'Approximately', th: 'ประมาณ' },
    { en: 'Especially', th: 'โดยเฉพาะ' },
    { en: 'Incredibly', th: 'อย่างเหลือเชื่อ' },
    { en: 'Quarterly', th: 'รายไตรมาส' },
    { en: 'Monthly', th: 'รายเดือน' },
    { en: 'Hourly', th: 'รายชั่วโมง' },
    { en: 'Daily', th: 'ทุกวัน' },
    { en: 'Weekly', th: 'รายสัปดาห์' },
    { en: 'Easily', th: 'อย่างง่ายดาย' },
    { en: 'Effectively', th: 'อย่างมีประสิทธิภาพ' },
    { en: 'Strictly', th: 'อย่างเข้มงวด' },
    { en: 'Professionally', th: 'อย่างเชี่ยวชาญ' },
    { en: 'Significantly', th: 'อย่างสำคัญ' },
    { en: 'Gradually', th: 'อย่างช้า ๆ' },
    { en: 'Sharply', th: 'อย่างรวดเร็ว' },
    { en: 'hello', th: 'สวัสดี' },
    { en: 'goodbye', th: 'ลาก่อน' },
    { en: 'thank you', th: 'ขอบคุณ' },
    { en: 'please', th: 'กรุณา' },
    { en: 'sorry', th: 'ขอโทษ' },
    { en: 'house', th: 'บ้าน' },
    { en: 'car', th: 'รถยนต์' },
    { en: 'table', th: 'โต๊ะ' },
    { en: 'chair', th: 'เก้าอี้' },
    { en: 'door', th: 'ประตู' },
    { en: 'window', th: 'หน้าต่าง' },
    { en: 'phone', th: 'โทรศัพท์' },
    { en: 'computer', th: 'คอมพิวเตอร์' },
    { en: 'eat', th: 'กิน' },
    { en: 'drink', th: 'ดื่ม' },
    { en: 'sleep', th: 'นอน' },
    { en: 'walk', th: 'เดิน' },
    { en: 'run', th: 'วิ่ง' },
    { en: 'jump', th: 'กระโดด' },
    { en: 'sit', th: 'นั่ง' },
    { en: 'stand', th: 'ยืน' },
    { en: 'read', th: 'อ่าน' },
    { en: 'write', th: 'เขียน' },
    { en: 'listen', th: 'ฟัง' },
    { en: 'speak', th: 'พูด' },
    { en: 'happy', th: 'มีความสุข' },
    { en: 'sad', th: 'เศร้า' },
    { en: 'angry', th: 'โกรธ' },
    { en: 'tired', th: 'เหนื่อย' },
    { en: 'hungry', th: 'หิว' },
    { en: 'thirsty', th: 'กระหาย' },
    { en: 'hot', th: 'ร้อน' },
    { en: 'cold', th: 'หนาว' },
    { en: 'big', th: 'ใหญ่' },
    { en: 'small', th: 'เล็ก' },
    { en: 'tall', th: 'สูง' },
    { en: 'short', th: 'เตี้ย' },
    { en: 'fast', th: 'เร็ว' },
    { en: 'slow', th: 'ช้า' },
    { en: 'beautiful', th: 'สวย' },
    { en: 'ugly', th: 'น่าเกลียด' },
    { en: 'new', th: 'ใหม่' },
    { en: 'old', th: 'เก่า' },
    { en: 'good', th: 'ดี' },
    { en: 'bad', th: 'แย่' },
    { en: 'expensive', th: 'แพง' },
    { en: 'cheap', th: 'ถูก' },
    { en: 'day', th: 'วัน' },
    { en: 'night', th: 'คืน' },
    { en: 'sun', th: 'พระอาทิตย์' },
    { en: 'moon', th: 'พระจันทร์' },
    { en: 'star', th: 'ดาว' },
    { en: 'sky', th: 'ท้องฟ้า' },
    { en: 'cloud', th: 'เมฆ' },
    { en: 'rain', th: 'ฝน' },
    { en: 'wind', th: 'ลม' },
    { en: 'snow', th: 'หิมะ' },
    { en: 'mountain', th: 'ภูเขา' },
    { en: 'river', th: 'แม่น้ำ' },
    { en: 'sea', th: 'ทะเล' },
    { en: 'beach', th: 'ชายหาด' },
    { en: 'forest', th: 'ป่า' },
    { en: 'tree', th: 'ต้นไม้' },
    { en: 'flower', th: 'ดอกไม้' },
    { en: 'grass', th: 'หญ้า' },
    { en: 'father', th: 'พ่อ' },
    { en: 'mother', th: 'แม่' },
    { en: 'sister', th: 'พี่สาว' },
    { en: 'brother', th: 'พี่ชาย' },
    { en: 'friend', th: 'เพื่อน' },
    { en: 'teacher', th: 'ครู' },
    { en: 'student', th: 'นักเรียน' },
    { en: 'doctor', th: 'หมอ' },
    { en: 'nurse', th: 'พยาบาล' },
    { en: 'police', th: 'ตำรวจ' },
    { en: 'driver', th: 'คนขับรถ' },
    { en: 'cook', th: 'พ่อครัว' },
    { en: 'farmer', th: 'ชาวนา' },
    { en: 'artist', th: 'ศิลปิน' },
    { en: 'singer', th: 'นักร้อง' },
    { en: 'actor', th: 'นักแสดง' },
    { en: 'writer', th: 'นักเขียน' },
    { en: 'engineer', th: 'วิศวกร' },
    { en: 'scientist', th: 'นักวิทยาศาสตร์' },
    { en: 'head', th: 'หัว' },
    { en: 'face', th: 'ใบหน้า' },
    { en: 'eye', th: 'ตา' },
    { en: 'nose', th: 'จมูก' },
    { en: 'mouth', th: 'ปาก' },
    { en: 'ear', th: 'หู' },
    { en: 'hair', th: 'ผม' },
    { en: 'hand', th: 'มือ' },
    { en: 'foot', th: 'เท้า' },
    { en: 'leg', th: 'ขา' },
    { en: 'arm', th: 'แขน' },
    { en: 'finger', th: 'นิ้วมือ' },
    { en: 'toe', th: 'นิ้วเท้า' },
    { en: 'heart', th: 'หัวใจ' },
    { en: 'brain', th: 'สมอง' },
    { en: 'blood', th: 'เลือด' },
    { en: 'bone', th: 'กระดูก' },
    { en: 'skin', th: 'ผิวหนัง' },
    { en: 'light', th: 'แสง' },
    { en: 'dark', th: 'มืด' },
    { en: 'strong', th: 'แข็งแรง' },
    { en: 'weak', th: 'อ่อนแอ' },
    { en: 'clean', th: 'สะอาด' },
    { en: 'dirty', th: 'สกปรก' },
    { en: 'early', th: 'เช้า' },
    { en: 'late', th: 'สาย' },
    { en: 'child', th: 'เด็ก' },
    { en: 'adult', th: 'ผู้ใหญ่' },
    { en: 'music', th: 'ดนตรี' },
    { en: 'movie', th: 'ภาพยนตร์' },
    { en: 'game', th: 'เกม' },
    { en: 'exercise', th: 'ออกกำลังกาย' },
    { en: 'work', th: 'งาน' },
    { en: 'study', th: 'ศึกษา' },
    { en: 'play', th: 'เล่น' },
    { en: 'water', th: 'น้ำ' },
    { en: 'fire', th: 'ไฟ' },
    { en: 'earth', th: 'ดิน' },
    { en: 'air', th: 'อากาศ' },
    { en: 'bird', th: 'นก' },
    { en: 'fish', th: 'ปลา' },
    { en: 'dog', th: 'สุนัข' },
    { en: 'cat', th: 'แมว' },
    { en: 'insect', th: 'แมลง' },
    { en: 'food', th: 'อาหาร' },
    { en: 'fruit', th: 'ผลไม้' },
    { en: 'vegetable', th: 'ผัก' },
    { en: 'meat', th: 'เนื้อสัตว์' },
    { en: 'bread', th: 'ขนมปัง' },
    { en: 'rice', th: 'ข้าว' },
    { en: 'milk', th: 'นม' },
    { en: 'juice', th: 'น้ำผลไม้' },
    { en: 'coffee', th: 'กาแฟ' },
    { en: 'tea', th: 'ชา' },
    { en: 'shirt', th: 'เสื้อ' },
    { en: 'pants', th: 'กางเกง' },
    { en: 'shoes', th: 'รองเท้า' },
    { en: 'hat', th: 'หมวก' },
    { en: 'watch', th: 'นาฬิกาข้อมือ' },
    { en: 'money', th: 'เงิน' },
    { en: 'key', th: 'กุญแจ' },
    { en: 'ticket', th: 'ตั๋ว' },
    { en: 'train', th: 'รถไฟ' },
    { en: 'airplane', th: 'เครื่องบิน' },
    { en: 'boat', th: 'เรือ' },
    { en: 'bicycle', th: 'จักรยาน' },
    { en: 'bus', th: 'รถบัส' },
    { en: 'road', th: 'ถนน' },
    { en: 'bridge', th: 'สะพาน' },
    { en: 'building', th: 'อาคาร' },
    { en: 'room', th: 'ห้อง' },
    { en: 'kitchen', th: 'ห้องครัว' },
    { en: 'bathroom', th: 'ห้องน้ำ' },
    { en: 'bedroom', th: 'ห้องนอน' },
    { en: 'living room', th: 'ห้องนั่งเล่น' },
    { en: 'garden', th: 'สวน' },
    { en: 'park', th: 'สวนสาธารณะ' },
    { en: 'city', th: 'เมือง' },
    { en: 'village', th: 'หมู่บ้าน' },
    { en: 'country', th: 'ประเทศ' },
    { en: 'island', th: 'เกาะ' },
    { en: 'ocean', th: 'มหาสมุทร' },
    { en: 'desert', th: 'ทะเลทราย' },
    { en: 'lake', th: 'ทะเลสาบ' },
    { en: 'flower pot', th: 'กระถางต้นไม้' },
    { en: 'bush', th: 'พุ่มไม้' },
    { en: 'leaf', th: 'ใบไม้' },
    { en: 'fruit tree', th: 'ต้นผลไม้' },
    { en: 'coconut tree', th: 'ต้นมะพร้าว' },
    { en: 'traffic', th: 'การจราจร' },
    { en: 'street light', th: 'ไฟถนน' },
    { en: 'signal', th: 'สัญญาณ' },
    { en: 'map', th: 'แผนที่' },
    { en: 'compass', th: 'เข็มทิศ' },
    { en: 'bagpack', th: 'กระเป๋าเป้' },
    { en: 'umbrella', th: 'ร่ม' },
    { en: 'glasses', th: 'แว่นตา' },
    { en: 'ring', th: 'แหวน' },
    { en: 'bracelet', th: 'สร้อยข้อมือ' },
    { en: 'necklace', th: 'สร้อยคอ' },
    { en: 'earring', th: 'ต่างหู' },
    { en: 'mask', th: 'หน้ากาก' },
    { en: 'medicine', th: 'ยา' },
    { en: 'soap', th: 'สบู่' },
    { en: 'shampoo', th: 'แชมพู' },
    { en: 'towel', th: 'ผ้าเช็ดตัว' },
    { en: 'blanket', th: 'ผ้าห่ม' },
    { en: 'pillow', th: 'หมอน' },
    { en: 'fan', th: 'พัดลม' },
    { en: 'lamp', th: 'โคมไฟ' },
    { en: 'television', th: 'โทรทัศน์' },
    { en: 'radio', th: 'วิทยุ' },
    { en: 'refrigerator', th: 'ตู้เย็น' },
    { en: 'oven', th: 'เตาอบ' },
    { en: 'stove', th: 'เตาแก๊ส' },
    { en: 'sink', th: 'อ่างล้างจาน' },
    { en: 'cup', th: 'ถ้วย' },
    { en: 'plate', th: 'จาน' },
    { en: 'fork', th: 'ส้อม' },
    { en: 'salad', th: 'สลัด' },
    { en: 'soup', th: 'ซุป' },
    { en: 'noodle', th: 'บะหมี่' },
    { en: 'pasta', th: 'พาสต้า' },
    { en: 'pizza', th: 'พิซซ่า' },
    { en: 'hamburger', th: 'แฮมเบอร์เกอร์' },
    { en: 'sushi', th: 'ซูชิ' },
    { en: 'dessert', th: 'ของหวาน' },
    { en: 'cream', th: 'ครีม' },
    { en: 'yogurt', th: 'โยเกิร์ต' },
    { en: 'hospital', th: 'โรงพยาบาล' },
    { en: 'restaurant', th: 'ร้านอาหาร' },
    { en: 'airport', th: 'สนามบิน' },
    { en: 'library', th: 'ห้องสมุด' },
    { en: 'supermarket', th: 'ซุปเปอร์มาร์เก็ต' },
    { en: 'factory', th: 'โรงงาน' },
    { en: 'museum', th: 'พิพิธภัณฑ์' },
    { en: 'mall', th: 'ห้างสรรพสินค้า' },
    { en: 'stadium', th: 'สนามกีฬา' },
    { en: 'temple', th: 'วัด' },
    { en: 'motorcycle', th: 'มอเตอร์ไซค์' },
    { en: 'taxi', th: 'แท็กซี่' },
    { en: 'helicopter', th: 'เฮลิคอปเตอร์' },
    { en: 'truck', th: 'รถบรรทุก' },
    { en: 'van', th: 'รถตู้' },
    { en: 'subway', th: 'รถไฟใต้ดิน' },
    { en: 'ferry', th: 'เรือข้ามฟาก' },
    { en: 'rocket', th: 'จรวด' },
    { en: 'scooter', th: 'สกูตเตอร์' },
    { en: 'limousine', th: 'รถลีมูซีน' },
    { en: 'internet', th: 'อินเทอร์เน็ต' },
    { en: 'software', th: 'ซอฟต์แวร์' },
    { en: 'app', th: 'แอป' },
    { en: 'website', th: 'เว็บไซต์' },
    { en: 'database', th: 'ฐานข้อมูล' },
    { en: 'router', th: 'เราเตอร์' },
    { en: 'server', th: 'เซิร์ฟเวอร์' },
    { en: 'tablet', th: 'แท็บเล็ต' },
    { en: 'drone', th: 'โดรน' },
    { en: 'robot', th: 'หุ่นยนต์' },
    { en: 'football', th: 'ฟุตบอล' },
    { en: 'basketball', th: 'บาสเกตบอล' },
    { en: 'tennis', th: 'เทนนิส' },
    { en: 'golf', th: 'กอล์ฟ' },
    { en: 'swimming', th: 'ว่ายน้ำ' },
    { en: 'hiking', th: 'เดินป่า' },
    { en: 'yoga', th: 'โยคะ' },
    { en: 'chess', th: 'หมากรุก' },
    { en: 'dance', th: 'เต้นรำ' },
    { en: 'fitness', th: 'ฟิตเนส' },
    { en: 'accountant', th: 'นักบัญชี' },
    { en: 'programmer', th: 'นักเขียนโปรแกรม' },
    { en: 'lawyer', th: 'ทนายความ' },
    { en: 'architect', th: 'สถาปนิก' },
    { en: 'journalist', th: 'นักข่าว' },
    { en: 'dentist', th: 'ทันตแพทย์' },
    { en: 'pilot', th: 'นักบิน' },
    { en: 'designer', th: 'นักออกแบบ' },
    { en: 'electrician', th: 'ช่างไฟฟ้า' },
    { en: 'plumber', th: 'ช่างประปา' },
    { en: 'minute', th: 'นาที' },
    { en: 'hour', th: 'ชั่วโมง' },
    { en: 'week', th: 'สัปดาห์' },
    { en: 'month', th: 'เดือน' },
    { en: 'year', th: 'ปี' },
    { en: 'century', th: 'ศตวรรษ' },
    { en: 'spring', th: 'ฤดูใบไม้ผลิ' },
    { en: 'summer', th: 'ฤดูร้อน' },
    { en: 'autumn', th: 'ฤดูใบไม้ร่วง' },
    { en: 'winter', th: 'ฤดูหนาว' },
    { en: 'concrete', th: 'คอนกรีต' },
    { en: 'plastic', th: 'พลาสติก' },
    { en: 'metal', th: 'โลหะ' },
    { en: 'glass', th: 'แก้ว' },
    { en: 'rubber', th: 'ยาง' },
    { en: 'ceramic', th: 'เซรามิก' },
    { en: 'aluminum', th: 'อลูมิเนียม' },
    { en: 'steel', th: 'เหล็กกล้า' },
    { en: 'cotton', th: 'ผ้าฝ้าย' },
    { en: 'silk', th: 'ผ้าไหม' },
    { en: 'vitamin', th: 'วิตามิน' },
    { en: 'prescription', th: 'ใบสั่งยา' },
    { en: 'disease', th: 'โรค' },
    { en: 'pain', th: 'ความเจ็บปวด' },
    { en: 'symptom', th: 'อาการ' },
    { en: 'treatment', th: 'การรักษา' },
    { en: 'pharmacy', th: 'ร้านขายยา' },
    { en: 'clinic', th: 'คลินิก' },
    { en: 'surgery', th: 'การผ่าตัด' },
    { en: 'therapy', th: 'การบำบัด' },
    { en: 'culture', th: 'วัฒนธรรม' },
    { en: 'language', th: 'ภาษา' },
    { en: 'tradition', th: 'ประเพณี' },
    { en: 'history', th: 'ประวัติศาสตร์' },
    { en: 'education', th: 'การศึกษา' },
    { en: 'politics', th: 'การเมือง' },
    { en: 'economy', th: 'เศรษฐกิจ' },
    { en: 'society', th: 'สังคม' },
    { en: 'universe', th: 'จักรวาล' },
    { en: 'galaxy', th: 'กาแลคซี' },
    { en: 'elephant', th: 'ช้าง' },
    { en: 'tiger', th: 'เสือ' },
    { en: 'lion', th: 'สิงโต' },
    { en: 'monkey', th: 'ลิง' },
    { en: 'rabbit', th: 'กระต่าย' },
    { en: 'snake', th: 'งู' },
    { en: 'turtle', th: 'เต่า' },
    { en: 'giraffe', th: 'ยีราฟ' },
    { en: 'crocodile', th: 'จระเข้' },
    { en: 'dolphin', th: 'โลมา' },
    { en: 'shark', th: 'ฉลาม' },
    { en: 'butterfly', th: 'ผีเสื้อ' },
    { en: 'ant', th: 'มด' },
    { en: 'bee', th: 'ผึ้ง' },
    { en: 'frog', th: 'กบ' },

    // ผลไม้และพืชเฉพาะ
    { en: 'banana', th: 'กล้วย' },
    { en: 'apple', th: 'แอปเปิ้ล' },
    { en: 'orange', th: 'ส้ม' },
    { en: 'strawberry', th: 'สตรอเบอร์รี่' },
    { en: 'grape', th: 'องุ่น' },
    { en: 'watermelon', th: 'แตงโม' },
    { en: 'pineapple', th: 'สับปะรด' },
    { en: 'mango', th: 'มะม่วง' },
    { en: 'durian', th: 'ทุเรียน' },
    { en: 'papaya', th: 'มะละกอ' },
    { en: 'coconut', th: 'มะพร้าว' },
    { en: 'lychee', th: 'ลิ้นจี่' },
    { en: 'longan', th: 'ลำไย' },
    { en: 'rose', th: 'ดอกกุหลาบ' },
    { en: 'sunflower', th: 'ดอกทานตะวัน' },

    // สี
    { en: 'red', th: 'สีแดง' },
    { en: 'green', th: 'สีเขียว' },
    { en: 'blue', th: 'สีน้ำเงิน' },
    { en: 'yellow', th: 'สีเหลือง' },
    { en: 'white', th: 'สีขาว' },
    { en: 'black', th: 'สีดำ' },
    { en: 'orange', th: 'สีส้ม' },
    { en: 'purple', th: 'สีม่วง' },
    { en: 'pink', th: 'สีชมพู' },
    { en: 'brown', th: 'สีน้ำตาล' },
    { en: 'grey', th: 'สีเทา' },
    { en: 'gold', th: 'สีทอง' },
    { en: 'silver', th: 'สีเงิน' },

    // ประเทศและทวีป
    { en: 'Thailand', th: 'ประเทศไทย' },
    { en: 'Japan', th: 'ประเทศญี่ปุ่น' },
    { en: 'China', th: 'ประเทศจีน' },
    { en: 'America', th: 'อเมริกา' },
    { en: 'England', th: 'อังกฤษ' },
    { en: 'France', th: 'ฝรั่งเศส' },
    { en: 'Germany', th: 'เยอรมนี' },
    { en: 'Italy', th: 'อิตาลี' },
    { en: 'Australia', th: 'ออสเตรเลีย' },
    { en: 'Canada', th: 'แคนาดา' },
    { en: 'India', th: 'อินเดีย' },
    { en: 'Russia', th: 'รัสเซีย' },
    { en: 'Asia', th: 'เอเชีย' },
    { en: 'Europe', th: 'ยุโรป' },
    { en: 'Africa', th: 'แอฟริกา' },

    // เทคโนโลยีสมัยใหม่
    { en: 'smartphone', th: 'สมาร์ทโฟน' },
    { en: 'social media', th: 'สื่อสังคมออนไลน์' },
    { en: 'artificial intelligence', th: 'ปัญญาประดิษฐ์' },
    { en: 'virtual reality', th: 'ความเป็นจริงเสมือน' },
    { en: 'blockchain', th: 'บล็อกเชน' },
    { en: 'cryptocurrency', th: 'สกุลเงินดิจิทัล' },
    { en: 'streaming', th: 'การสตรีม' },
    { en: 'podcast', th: 'พอดแคสต์' },
    { en: 'cloud computing', th: 'การประมวลผลแบบคลาวด์' },
    { en: 'wearable', th: 'อุปกรณ์สวมใส่' },
    { en: '3D printing', th: 'การพิมพ์สามมิติ' },

    // ครอบครัวเพิ่มเติม
    { en: 'grandfather', th: 'ปู่/ตา' },
    { en: 'grandmother', th: 'ย่า/ยาย' },
    { en: 'grandson', th: 'หลานชาย' },
    { en: 'granddaughter', th: 'หลานสาว' },
    { en: 'uncle', th: 'ลุง/อา' },
    { en: 'aunt', th: 'ป้า/น้า' },
    { en: 'cousin', th: 'ลูกพี่ลูกน้อง' },
    { en: 'nephew', th: 'หลานชาย (ลูกพี่/น้อง)' },
    { en: 'niece', th: 'หลานสาว (ลูกพี่/น้อง)' },
    { en: 'son', th: 'ลูกชาย' },
    { en: 'daughter', th: 'ลูกสาว' },
    { en: 'husband', th: 'สามี' },
    { en: 'wife', th: 'ภรรยา' },

    // อาชีพเพิ่มเติม
    { en: 'chef', th: 'เชฟ' },
    { en: 'photographer', th: 'ช่างภาพ' },
    { en: 'manager', th: 'ผู้จัดการ' },
    { en: 'receptionist', th: 'พนักงานต้อนรับ' },
    { en: 'firefighter', th: 'นักดับเพลิง' },
    { en: 'hairdresser', th: 'ช่างทำผม' },
    { en: 'translator', th: 'นักแปลภาษา' },
    { en: 'gardener', th: 'คนสวน' },
    { en: 'fisherman', th: 'ชาวประมง' },
    { en: 'bartender', th: 'บาร์เทนเดอร์' },
    { en: 'astronaut', th: 'นักบินอวกาศ' },
    { en: 'professor', th: 'ศาสตราจารย์' },

    // อารมณ์และความรู้สึก
    { en: 'joy', th: 'ความสุข' },
    { en: 'fear', th: 'ความกลัว' },
    { en: 'excitement', th: 'ความตื่นเต้น' },
    { en: 'jealousy', th: 'ความอิจฉา' },
    { en: 'anxiety', th: 'ความวิตกกังวล' },
    { en: 'boredom', th: 'ความเบื่อ' },
    { en: 'pride', th: 'ความภูมิใจ' },
    { en: 'guilt', th: 'ความรู้สึกผิด' },
    { en: 'shame', th: 'ความอับอาย' },
    { en: 'surprise', th: 'ความประหลาดใจ' },
    { en: 'confusion', th: 'ความสับสน' },

    // ตัวเลขและจำนวน
    { en: 'one', th: 'หนึ่ง' },
    { en: 'two', th: 'สอง' },
    { en: 'three', th: 'สาม' },
    { en: 'hundred', th: 'ร้อย' },
    { en: 'thousand', th: 'พัน' },
    { en: 'million', th: 'ล้าน' },
    { en: 'first', th: 'ที่หนึ่ง/แรก' },
    { en: 'second', th: 'ที่สอง' },
    { en: 'third', th: 'ที่สาม' },
    { en: 'half', th: 'ครึ่ง' },
    { en: 'double', th: 'สองเท่า' },

    // เครื่องดื่ม
    { en: 'water', th: 'น้ำ' },
    { en: 'soda', th: 'น้ำอัดลม' },
    { en: 'wine', th: 'ไวน์' },
    { en: 'beer', th: 'เบียร์' },
    { en: 'whiskey', th: 'วิสกี้' },
    { en: 'lemonade', th: 'น้ำมะนาว' },
    { en: 'smoothie', th: 'สมูทตี้' },
    { en: 'cocktail', th: 'ค็อกเทล' },
    { en: 'milkshake', th: 'มิลค์เชค' },
    { en: 'bubble tea', th: 'ชานมไข่มุก' },
    { en: 'coconut water', th: 'น้ำมะพร้าว' },

    // ธุรกิจและการเงิน
    { en: 'bank', th: 'ธนาคาร' },
    { en: 'credit card', th: 'บัตรเครดิต' },
    { en: 'loan', th: 'เงินกู้' },
    { en: 'investment', th: 'การลงทุน' },
    { en: 'insurance', th: 'ประกันภัย' },
    { en: 'tax', th: 'ภาษี' },
    { en: 'budget', th: 'งบประมาณ' },
    { en: 'salary', th: 'เงินเดือน' },
    { en: 'profit', th: 'กำไร' },
    { en: 'loss', th: 'ขาดทุน' },
    { en: 'contract', th: 'สัญญา' },
    { en: 'stock', th: 'หุ้น' },

    // เครื่องปรุงและเครื่องเทศ
    { en: 'salt', th: 'เกลือ' },
    { en: 'pepper', th: 'พริกไทย' },
    { en: 'sugar', th: 'น้ำตาล' },
    { en: 'vinegar', th: 'น้ำส้มสายชู' },
    { en: 'chili', th: 'พริก' },
    { en: 'garlic', th: 'กระเทียม' },
    { en: 'ginger', th: 'ขิง' },
    { en: 'basil', th: 'โหระพา' },
    { en: 'cinnamon', th: 'อบเชย' },
    { en: 'soy sauce', th: 'ซอสถั่วเหลือง' },
    { en: 'fish sauce', th: 'น้ำปลา' },
    { en: 'oyster sauce', th: 'ซอสหอยนางรม' },

    // กีฬาและกิจกรรม
    { en: 'volleyball', th: 'วอลเลย์บอล' },
    { en: 'baseball', th: 'เบสบอล' },
    { en: 'bowling', th: 'โบว์ลิ่ง' },
    { en: 'skiing', th: 'สกี' },
    { en: 'surfing', th: 'เซิร์ฟ' },
    { en: 'skating', th: 'สเก็ต' },
    { en: 'archery', th: 'ยิงธนู' },
    { en: 'climbing', th: 'ปีนผา' },
    { en: 'diving', th: 'ดำน้ำ' },
    { en: 'fishing', th: 'ตกปลา' },
    { en: 'camping', th: 'การตั้งแคมป์' },

    // เพิ่มเติม
    { en: 'rainbow', th: 'รุ้ง' },
    { en: 'lightning', th: 'ฟ้าผ่า' },
    { en: 'thunder', th: 'ฟ้าร้อง' },
    { en: 'storm', th: 'พายุ' },
    { en: 'sunshine', th: 'แสงแดด' },
    { en: 'shadow', th: 'เงา' },
    { en: 'dream', th: 'ความฝัน' },
    { en: 'love', th: 'ความรัก' },
    { en: 'luck', th: 'โชค' },
    { en: 'freedom', th: 'อิสรภาพ' },
    { en: 'peace', th: 'สันติภาพ' },
    { en: 'smile', th: 'รอยยิ้ม' },
    { en: 'tear', th: 'น้ำตา' },
    { en: 'secret', th: 'ความลับ' },
    { en: 'password', th: 'รหัสผ่าน' },
    { en: 'memory', th: 'ความทรงจำ' },
    { en: 'message', th: 'ข้อความ' },
    // เครื่องดนตรี
    { en: 'piano', th: 'เปียโน' },
    { en: 'guitar', th: 'กีตาร์' },
    { en: 'violin', th: 'ไวโอลิน' },
    { en: 'flute', th: 'ขลุ่ย' },
    { en: 'drums', th: 'กลอง' },
    { en: 'saxophone', th: 'แซ็กโซโฟน' },
    { en: 'trumpet', th: 'ทรัมเป็ต' },
    { en: 'harp', th: 'พิณ' },
    { en: 'cello', th: 'เชลโล' },
    { en: 'harmonica', th: 'ฮาร์โมนิกา' },

    // วิชาการศึกษา
    { en: 'mathematics', th: 'คณิตศาสตร์' },
    { en: 'biology', th: 'ชีววิทยา' },
    { en: 'chemistry', th: 'เคมี' },
    { en: 'physics', th: 'ฟิสิกส์' },
    { en: 'geography', th: 'ภูมิศาสตร์' },
    { en: 'literature', th: 'วรรณคดี' },
    { en: 'philosophy', th: 'ปรัชญา' },
    { en: 'psychology', th: 'จิตวิทยา' },
    { en: 'sociology', th: 'สังคมวิทยา' },
    { en: 'anthropology', th: 'มานุษยวิทยา' },

    // ร่างกายมนุษย์เพิ่มเติม
    { en: 'shoulder', th: 'ไหล่' },
    { en: 'elbow', th: 'ข้อศอก' },
    { en: 'wrist', th: 'ข้อมือ' },
    { en: 'knee', th: 'หัวเข่า' },
    { en: 'ankle', th: 'ข้อเท้า' },
    { en: 'spine', th: 'กระดูกสันหลัง' },
    { en: 'waist', th: 'เอว' },
    { en: 'hip', th: 'สะโพก' },
    { en: 'chest', th: 'หน้าอก' },
    { en: 'stomach', th: 'กระเพาะอาหาร' },
    { en: 'liver', th: 'ตับ' },
    { en: 'lung', th: 'ปอด' },
    { en: 'kidney', th: 'ไต' },

    // อาหารเพิ่มเติม
    { en: 'curry', th: 'แกง' },
    { en: 'steak', th: 'สเต็ก' },
    { en: 'omelet', th: 'ไข่เจียว' },
    { en: 'pancake', th: 'แพนเค้ก' },
    { en: 'dumpling', th: 'เกี๊ยว' },
    { en: 'stir-fry', th: 'ผัด' },
    { en: 'porridge', th: 'โจ๊ก' },
    { en: 'cereal', th: 'ซีเรียล' },
    { en: 'honey', th: 'น้ำผึ้ง' },
    { en: 'jam', th: 'แยม' },
    { en: 'pastry', th: 'ขนมอบ' },
    { en: 'cookies', th: 'คุกกี้' },
    { en: 'chocolate', th: 'ช็อกโกแลต' },

    // ดอกไม้และพืช
    { en: 'orchid', th: 'กล้วยไม้' },
    { en: 'lotus', th: 'ดอกบัว' },
    { en: 'jasmine', th: 'มะลิ' },
    { en: 'lily', th: 'ดอกลิลลี่' },
    { en: 'tulip', th: 'ดอกทิวลิป' },
    { en: 'daisy', th: 'ดอกเดซี่' },
    { en: 'cactus', th: 'กระบองเพชร' },
    { en: 'fern', th: 'เฟิร์น' },
    { en: 'moss', th: 'มอส' },
    { en: 'bamboo', th: 'ไผ่' },
    { en: 'pine', th: 'สน' },
    { en: 'oak', th: 'ต้นโอ๊ก' },

    // สัตว์น้ำและสัตว์อื่นๆ เพิ่มเติม
    { en: 'octopus', th: 'ปลาหมึก' },
    { en: 'squid', th: 'หมึกกล้วย' },
    { en: 'shrimp', th: 'กุ้ง' },
    { en: 'crab', th: 'ปู' },
    { en: 'jellyfish', th: 'แมงกะพรุน' },
    { en: 'seahorse', th: 'ม้าน้ำ' },
    { en: 'starfish', th: 'ปลาดาว' },
    { en: 'coral', th: 'ปะการัง' },
    { en: 'penguin', th: 'เพนกวิน' },
    { en: 'fox', th: 'สุนัขจิ้งจอก' },
    { en: 'wolf', th: 'หมาป่า' },
    { en: 'owl', th: 'นกฮูก' },
    { en: 'bat', th: 'ค้างคาว' },

    // วัสดุและเนื้อผ้า
    { en: 'leather', th: 'หนัง' },
    { en: 'wool', th: 'ขนสัตว์' },
    { en: 'nylon', th: 'ไนลอน' },
    { en: 'polyester', th: 'โพลีเอสเตอร์' },
    { en: 'velvet', th: 'กำมะหยี่' },
    { en: 'denim', th: 'ผ้ายีนส์' },
    { en: 'linen', th: 'ผ้าลินิน' },
    { en: 'marble', th: 'หินอ่อน' },
    { en: 'granite', th: 'หินแกรนิต' },
    { en: 'bronze', th: 'ทองสัมฤทธิ์' },
    { en: 'copper', th: 'ทองแดง' },
    { en: 'titanium', th: 'ไทเทเนียม' },

    // เครื่องมือและอุปกรณ์
    { en: 'hammer', th: 'ค้อน' },
    { en: 'screwdriver', th: 'ไขควง' },
    { en: 'wrench', th: 'ประแจ' },
    { en: 'drill', th: 'สว่าน' },
    { en: 'saw', th: 'เลื่อย' },
    { en: 'ladder', th: 'บันได' },
    { en: 'tape measure', th: 'ตลับเมตร' },
    { en: 'pliers', th: 'คีม' },
    { en: 'shovel', th: 'พลั่ว' },
    { en: 'wheelbarrow', th: 'รถเข็น' },
    { en: 'trowel', th: 'เกรียง' },
    { en: 'chisel', th: 'สิ่ว' },

    // อวกาศและดาราศาสตร์
    { en: 'planet', th: 'ดาวเคราะห์' },
    { en: 'asteroid', th: 'ดาวเคราะห์น้อย' },
    { en: 'comet', th: 'ดาวหาง' },
    { en: 'satellite', th: 'ดาวเทียม' },
    { en: 'orbit', th: 'วงโคจร' },
    { en: 'meteor', th: 'ดาวตก' },
    { en: 'constellation', th: 'กลุ่มดาว' },
    { en: 'telescope', th: 'กล้องดูดาว' },
    { en: 'spacecraft', th: 'ยานอวกาศ' },
    { en: 'astronomer', th: 'นักดาราศาสตร์' },
    { en: 'gravity', th: 'แรงโน้มถ่วง' },
    { en: 'black hole', th: 'หลุมดำ' },

    // ภัยธรรมชาติ
    { en: 'earthquake', th: 'แผ่นดินไหว' },
    { en: 'tsunami', th: 'สึนามิ' },
    { en: 'hurricane', th: 'พายุเฮอริเคน' },
    { en: 'tornado', th: 'พายุทอร์นาโด' },
    { en: 'drought', th: 'ความแห้งแล้ง' },
    { en: 'flood', th: 'น้ำท่วม' },
    { en: 'wildfire', th: 'ไฟป่า' },
    { en: 'landslide', th: 'ดินถล่ม' },
    { en: 'volcanic eruption', th: 'ภูเขาไฟระเบิด' },
    { en: 'avalanche', th: 'หิมะถล่ม' },
    { en: 'blizzard', th: 'พายุหิมะ' },

    // เสื้อผ้าและแฟชั่น
    { en: 'jacket', th: 'เสื้อแจ็คเก็ต' },
    { en: 'coat', th: 'เสื้อโค้ท' },
    { en: 'sweater', th: 'เสื้อไหมพรม' },
    { en: 'skirt', th: 'กระโปรง' },
    { en: 'dress', th: 'ชุดเดรส' },
    { en: 'jeans', th: 'กางเกงยีนส์' },
    { en: 'shorts', th: 'กางเกงขาสั้น' },
    { en: 'socks', th: 'ถุงเท้า' },
    { en: 'tie', th: 'เนคไท' },
    { en: 'bow tie', th: 'หูกระต่าย' },
    { en: 'sandals', th: 'รองเท้าแตะ' },
    { en: 'boots', th: 'รองเท้าบูท' },
    { en: 'sneakers', th: 'รองเท้าผ้าใบ' },

    // การแพทย์และสุขภาพ
    { en: 'headache', th: 'ปวดหัว' },
    { en: 'fever', th: 'ไข้' },
    { en: 'allergy', th: 'ภูมิแพ้' },
    { en: 'infection', th: 'การติดเชื้อ' },
    { en: 'bandage', th: 'ผ้าพันแผล' },
    { en: 'syringe', th: 'หลอดฉีดยา' },
    { en: 'stethoscope', th: 'หูฟังแพทย์' },
    { en: 'wheelchair', th: 'รถเข็นคนไข้' },
    { en: 'blood pressure', th: 'ความดันโลหิต' },
    { en: 'vaccination', th: 'การฉีดวัคซีน' },
    { en: 'antibiotic', th: 'ยาปฏิชีวนะ' },
    { en: 'ointment', th: 'ยาขี้ผึ้ง' },

    // แมลงและสัตว์เล็ก
    { en: 'mosquito', th: 'ยุง' },
    { en: 'fly', th: 'แมลงวัน' },
    { en: 'cockroach', th: 'แมลงสาบ' },
    { en: 'spider', th: 'แมงมุม' },
    { en: 'beetle', th: 'แมลงปีกแข็ง' },
    { en: 'ladybug', th: 'เต่าทอง' },
    { en: 'grasshopper', th: 'ตั๊กแตน' },
    { en: 'dragonfly', th: 'แมลงปอ' },
    { en: 'centipede', th: 'ตะขาบ' },
    { en: 'scorpion', th: 'แมงป่อง' },
    { en: 'moth', th: 'ผีเสื้อกลางคืน' },
    { en: 'worm', th: 'หนอน' },

    // คำกริยาเพิ่มเติม
    { en: 'swim', th: 'ว่ายน้ำ' },
    { en: 'fly', th: 'บิน' },
    { en: 'climb', th: 'ปีน' },
    { en: 'dance', th: 'เต้นรำ' },
    { en: 'laugh', th: 'หัวเราะ' },
    { en: 'cry', th: 'ร้องไห้' },
    { en: 'sing', th: 'ร้องเพลง' },
    { en: 'cook', th: 'ทำอาหาร' },
    { en: 'draw', th: 'วาดรูป' },
    { en: 'paint', th: 'ระบายสี' },
    { en: 'build', th: 'สร้าง' },
    { en: 'repair', th: 'ซ่อม' },
    { en: 'search', th: 'ค้นหา' },
    { en: 'find', th: 'พบ' },
    { en: 'lose', th: 'สูญเสีย' },
    { en: 'win', th: 'ชนะ' },
    { en: 'fail', th: 'ล้มเหลว' },
    { en: 'try', th: 'พยายาม' },
    { en: 'begin', th: 'เริ่มต้น' },
    { en: 'finish', th: 'เสร็จสิ้น' },

    // สถานที่เพิ่มเติม
    { en: 'gym', th: 'ยิม' },
    { en: 'cinema', th: 'โรงภาพยนตร์' },
    { en: 'zoo', th: 'สวนสัตว์' },
    { en: 'aquarium', th: 'พิพิธภัณฑ์สัตว์น้ำ' },
    { en: 'bakery', th: 'ร้านขนมปัง' },
    { en: 'butcher', th: 'ร้านขายเนื้อ' },
    { en: 'pharmacy', th: 'ร้านขายยา' },
    { en: 'post office', th: 'ไปรษณีย์' },
    { en: 'bank', th: 'ธนาคาร' },
    { en: 'police station', th: 'สถานีตำรวจ' },
    { en: 'fire station', th: 'สถานีดับเพลิง' },
    { en: 'playground', th: 'สนามเด็กเล่น' },
    { en: 'cemetery', th: 'สุสาน' },
    { en: 'convenience store', th: 'ร้านสะดวกซื้อ' },
    { en: 'marketplace', th: 'ตลาด' },

    // คำคุณศัพท์เพิ่มเติม
    { en: 'delicious', th: 'อร่อย' },
    { en: 'spicy', th: 'เผ็ด' },
    { en: 'sweet', th: 'หวาน' },
    { en: 'sour', th: 'เปรี้ยว' },
    { en: 'bitter', th: 'ขม' },
    { en: 'salty', th: 'เค็ม' },
    { en: 'deep', th: 'ลึก' },
    { en: 'shallow', th: 'ตื้น' },
    { en: 'wide', th: 'กว้าง' },
    { en: 'narrow', th: 'แคบ' },
    { en: 'loud', th: 'เสียงดัง' },
    { en: 'quiet', th: 'เงียบ' },
    { en: 'busy', th: 'ยุ่ง' },
    { en: 'free', th: 'ว่าง' },
    { en: 'comfortable', th: 'สบาย' },
    { en: 'dangerous', th: 'อันตราย' },
    { en: 'safe', th: 'ปลอดภัย' },
    { en: 'proud', th: 'ภูมิใจ' },
    { en: 'ashamed', th: 'อับอาย' },
    { en: 'curious', th: 'อยากรู้อยากเห็น' },

    // อาชีพเพิ่มเติม
    { en: 'baker', th: 'คนทำขนมปัง' },
    { en: 'butcher', th: 'คนขายเนื้อ' },
    { en: 'carpenter', th: 'ช่างไม้' },
    { en: 'mechanic', th: 'ช่างยนต์' },
    { en: 'tailor', th: 'ช่างตัดเสื้อ' },
    { en: 'sailor', th: 'กะลาสี' },
    { en: 'soldier', th: 'ทหาร' },
    { en: 'judge', th: 'ผู้พิพากษา' },
    { en: 'politician', th: 'นักการเมือง' },
    { en: 'secretary', th: 'เลขานุการ' },
    { en: 'accountant', th: 'นักบัญชี' },
    { en: 'chemist', th: 'นักเคมี' },
    { en: 'historian', th: 'นักประวัติศาสตร์' },
    { en: 'archaeologist', th: 'นักโบราณคดี' },
    { en: 'psychologist', th: 'นักจิตวิทยา' },

    // ยานพาหนะเพิ่มเติม
    { en: 'sailboat', th: 'เรือใบ' },
    { en: 'canoe', th: 'เรือแคนู' },
    { en: 'kayak', th: 'เรือคายัค' },
    { en: 'cruise ship', th: 'เรือสำราญ' },
    { en: 'ambulance', th: 'รถพยาบาล' },
    { en: 'tractor', th: 'รถแทรกเตอร์' },
    { en: 'bulldozer', th: 'รถเกรด' },
    { en: 'crane', th: 'รถเครน' },
    { en: 'forklift', th: 'รถยก' },
    { en: 'submarine', th: 'เรือดำน้ำ' },
    { en: 'spaceship', th: 'ยานอวกาศ' },
    { en: 'hot air balloon', th: 'บอลลูนอากาศร้อน' },
    { en: 'jet ski', th: 'เจ็ทสกี' },

    // คำเกี่ยวกับเทคโนโลยีเพิ่มเติม
    { en: 'algorithm', th: 'อัลกอริทึม' },
    { en: 'encryption', th: 'การเข้ารหัส' },
    { en: 'cybersecurity', th: 'ความปลอดภัยทางไซเบอร์' },
    { en: 'e-commerce', th: 'พาณิชย์อิเล็กทรอนิกส์' },
    { en: 'firewall', th: 'ไฟร์วอลล์' },
    { en: 'bandwidth', th: 'แบนด์วิดท์' },
    { en: 'pixel', th: 'พิกเซล' },
    { en: 'resolution', th: 'ความละเอียด' },
    { en: 'browser', th: 'เบราว์เซอร์' },
    { en: 'search engine', th: 'เครื่องมือค้นหา' },
    { en: 'augmented reality', th: 'ความเป็นจริงเสริม' },
    { en: 'hologram', th: 'ภาพสามมิติ' },

    // วันและเวลาเพิ่มเติม
    { en: 'dawn', th: 'รุ่งอรุณ' },
    { en: 'dusk', th: 'พลบค่ำ' },
    { en: 'noon', th: 'เที่ยงวัน' },
    { en: 'midnight', th: 'เที่ยงคืน' },
    { en: 'yesterday', th: 'เมื่อวาน' },
    { en: 'tomorrow', th: 'พรุ่งนี้' },
    { en: 'decade', th: 'ทศวรรษ' },
    { en: 'era', th: 'ยุค' },
    { en: 'anniversary', th: 'วันครบรอบ' },
    { en: 'schedule', th: 'ตารางเวลา' },
    { en: 'appointment', th: 'การนัดหมาย' },
    { en: 'period', th: 'ช่วงเวลา' },
    { en: 'sculpture', th: 'ประติมากรรม' },
    { en: 'pottery', th: 'เครื่องปั้นดินเผา' },
    { en: 'origami', th: 'ศิลปะพับกระดาษ' },
    { en: 'calligraphy', th: 'การคัดลายมือ' },
    { en: 'embroidery', th: 'งานปัก' },
    { en: 'sketch', th: 'ภาพร่าง' },
    { en: 'mural', th: 'ภาพฝาผนัง' },
    { en: 'collage', th: 'ศิลปะปะติด' },
    { en: 'weaving', th: 'การทอผ้า' },
    { en: 'craft', th: 'งานฝีมือ' },
    { en: 'mosaic', th: 'โมเสก' },
    { en: 'carving', th: 'การแกะสลัก' },
    { en: 'graffiti', th: 'ภาพวาดบนกำแพง' },
    { en: 'portrait', th: 'ภาพเหมือน' },
    { en: 'landscape', th: 'ภาพวิวทิวทัศน์' },

    // แร่ธาตุและอัญมณี
    { en: 'diamond', th: 'เพชร' },
    { en: 'ruby', th: 'ทับทิม' },
    { en: 'sapphire', th: 'ไพลิน' },
    { en: 'emerald', th: 'มรกต' },
    { en: 'jade', th: 'หยก' },
    { en: 'pearl', th: 'ไข่มุก' },
    { en: 'amethyst', th: 'อเมทิสต์' },
    { en: 'topaz', th: 'โทแพซ' },
    { en: 'opal', th: 'โอปอล' },
    { en: 'quartz', th: 'ควอตซ์' },
    { en: 'turquoise', th: 'เทอร์ควอยซ์' },
    { en: 'garnet', th: 'การ์เนต' },
    { en: 'crystal', th: 'คริสตัล' },
    { en: 'mineral', th: 'แร่ธาตุ' },
    { en: 'gemstone', th: 'อัญมณี' },

    // เทศกาลและประเพณี
    { en: 'festival', th: 'เทศกาล' },
    { en: 'carnival', th: 'งานรื่นเริง' },
    { en: 'parade', th: 'ขบวนแห่' },
    { en: 'ritual', th: 'พิธีกรรม' },
    { en: 'ceremony', th: 'พิธี' },
    { en: 'celebration', th: 'การฉลอง' },
    { en: 'tradition', th: 'ประเพณี' },
    { en: 'anniversary', th: 'วันครบรอบ' },
    { en: 'custom', th: 'ธรรมเนียม' },
    { en: 'wedding', th: 'งานแต่งงาน' },
    { en: 'funeral', th: 'งานศพ' },
    { en: 'graduation', th: 'พิธีจบการศึกษา' },
    { en: 'baptism', th: 'พิธีล้างบาป' },
    { en: 'pilgrimage', th: 'การแสวงบุญ' },
    { en: 'procession', th: 'ขบวนแห่' },

    // รูปทรงเรขาคณิต
    { en: 'triangle', th: 'สามเหลี่ยม' },
    { en: 'square', th: 'สี่เหลี่ยมจตุรัส' },
    { en: 'circle', th: 'วงกลม' },
    { en: 'rectangle', th: 'สี่เหลี่ยมผืนผ้า' },
    { en: 'hexagon', th: 'หกเหลี่ยม' },
    { en: 'pentagon', th: 'ห้าเหลี่ยม' },
    { en: 'octagon', th: 'แปดเหลี่ยม' },
    { en: 'cylinder', th: 'ทรงกระบอก' },
    { en: 'sphere', th: 'ทรงกลม' },
    { en: 'cone', th: 'ทรงกรวย' },
    { en: 'cube', th: 'ลูกบาศก์' },
    { en: 'pyramid', th: 'พีระมิด' },
    { en: 'prism', th: 'ปริซึม' },
    { en: 'diagonal', th: 'แนวทแยง' },
    { en: 'parallel', th: 'ขนาน' },

    // สถาปัตยกรรมและการก่อสร้าง
    { en: 'skyscraper', th: 'ตึกระฟ้า' },
    { en: 'arch', th: 'โค้ง' },
    { en: 'column', th: 'เสา' },
    { en: 'dome', th: 'โดม' },
    { en: 'foundation', th: 'ฐานราก' },
    { en: 'beam', th: 'คาน' },
    { en: 'facade', th: 'ด้านหน้าอาคาร' },
    { en: 'balcony', th: 'ระเบียง' },
    { en: 'terrace', th: 'ดาดฟ้า' },
    { en: 'mansion', th: 'คฤหาสน์' },
    { en: 'cottage', th: 'กระท่อม' },
    { en: 'hut', th: 'กระต๊อบ' },
    { en: 'staircase', th: 'บันไดเวียน' },
    { en: 'blueprint', th: 'แบบแปลน' },
    { en: 'scaffold', th: 'นั่งร้าน' },

    // สิ่งเหนือธรรมชาติและเทพนิยาย
    { en: 'fairy', th: 'นางฟ้า' },
    { en: 'wizard', th: 'พ่อมด' },
    { en: 'witch', th: 'แม่มด' },
    { en: 'dragon', th: 'มังกร' },
    { en: 'unicorn', th: 'ยูนิคอร์น' },
    { en: 'elf', th: 'เอลฟ์' },
    { en: 'goblin', th: 'ก็อบลิน' },
    { en: 'dwarf', th: 'คนแคระ' },
    { en: 'mermaid', th: 'นางเงือก' },
    { en: 'ghost', th: 'ผี' },
    { en: 'vampire', th: 'แวมไพร์' },
    { en: 'werewolf', th: 'มนุษย์หมาป่า' },
    { en: 'zombie', th: 'ซอมบี้' },
    { en: 'demon', th: 'ปีศาจ' },
    { en: 'angel', th: 'เทวดา' },

    // การเดินทางและการท่องเที่ยว
    { en: 'journey', th: 'การเดินทาง' },
    { en: 'voyage', th: 'การเดินเรือ' },
    { en: 'expedition', th: 'การเดินทางสำรวจ' },
    { en: 'adventure', th: 'การผจญภัย' },
    { en: 'tour', th: 'ทัวร์' },
    { en: 'itinerary', th: 'กำหนดการเดินทาง' },
    { en: 'destination', th: 'จุดหมายปลายทาง' },
    { en: 'souvenir', th: 'ของที่ระลึก' },
    { en: 'luggage', th: 'สัมภาระ' },
    { en: 'passport', th: 'หนังสือเดินทาง' },
    { en: 'visa', th: 'วีซ่า' },
    { en: 'customs', th: 'ศุลกากร' },
    { en: 'immigration', th: 'ตรวจคนเข้าเมือง' },
    { en: 'resort', th: 'รีสอร์ท' },
    { en: 'cabin', th: 'กระท่อมพักแรม' },

    // ดิจิทัลและเกม
    { en: 'console', th: 'เครื่องเกม' },
    { en: 'controller', th: 'ตัวควบคุมเกม' },
    { en: 'quest', th: 'ภารกิจ' },
    { en: 'arcade', th: 'ตู้เกมหยอดเหรียญ' },
    { en: 'avatar', th: 'ตัวละครในเกม' },
    { en: 'level', th: 'ระดับ' },
    { en: 'score', th: 'คะแนน' },
    { en: 'highscore', th: 'คะแนนสูงสุด' },
    { en: 'achievement', th: 'ความสำเร็จในเกม' },
    { en: 'checkpoint', th: 'จุดบันทึก' },
    { en: 'puzzle', th: 'ปริศนา' },
    { en: 'strategy', th: 'กลยุทธ์' },
    { en: 'simulation', th: 'การจำลอง' },
    { en: 'programmer', th: 'โปรแกรมเมอร์' },
    { en: 'developer', th: 'นักพัฒนา' },

    // รสชาติและประสบการณ์ทางประสาทสัมผัส
    { en: 'flavor', th: 'รสชาติ' },
    { en: 'aroma', th: 'กลิ่นหอม' },
    { en: 'texture', th: 'เนื้อสัมผัส' },
    { en: 'fragrance', th: 'กลิ่นหอม' },
    { en: 'scent', th: 'กลิ่น' },
    { en: 'stench', th: 'กลิ่นเหม็น' },
    { en: 'silky', th: 'เนียนนุ่มดุจไหม' },
    { en: 'rough', th: 'หยาบ' },
    { en: 'smooth', th: 'เรียบ' },
    { en: 'fuzzy', th: 'ฟู' },
    { en: 'crunchy', th: 'กรอบ' },
    { en: 'creamy', th: 'ครีมมี่' },
    { en: 'juicy', th: 'ฉ่ำน้ำ' },
    { en: 'tangy', th: 'เปรี้ยวฉุน' },
    { en: 'pungent', th: 'ฉุน' },

    // กฎหมายและระบบยุติธรรม
    { en: 'court', th: 'ศาล' },
    { en: 'verdict', th: 'คำตัดสิน' },
    { en: 'testimony', th: 'คำให้การ' },
    { en: 'witness', th: 'พยาน' },
    { en: 'evidence', th: 'หลักฐาน' },
    { en: 'punishment', th: 'การลงโทษ' },
    { en: 'defense', th: 'การป้องกัน' },
    { en: 'prosecution', th: 'การฟ้องร้อง' },
    { en: 'crime', th: 'อาชญากรรม' },
    { en: 'lawsuit', th: 'คดีความ' },
    { en: 'legality', th: 'ความชอบด้วยกฎหมาย' },
    { en: 'plaintiff', th: 'โจทก์' },
    { en: 'defendant', th: 'จำเลย' },
    { en: 'bail', th: 'การประกันตัว' },
    { en: 'jurisdiction', th: 'เขตอำนาจศาล' },

    // กีฬาและการแข่งขัน (เพิ่มเติม)
    { en: 'medal', th: 'เหรียญรางวัล' },
    { en: 'trophy', th: 'ถ้วยรางวัล' },
    { en: 'champion', th: 'แชมเปี้ยน' },
    { en: 'tournament', th: 'ทัวร์นาเมนต์' },
    { en: 'league', th: 'ลีก' },
    { en: 'referee', th: 'ผู้ตัดสิน' },
    { en: 'coach', th: 'ผู้ฝึกสอน' },
    { en: 'athlete', th: 'นักกีฬา' },
    { en: 'marathon', th: 'มาราธอน' },
    { en: 'triathlon', th: 'ไตรกีฬา' },
    { en: 'badminton', th: 'แบดมินตัน' },
    { en: 'rugby', th: 'รักบี้' },
    { en: 'wrestling', th: 'มวยปล้ำ' },
    { en: 'fencing', th: 'ดาบสากล' },
    { en: 'gymnastics', th: 'ยิมนาสติก' },

    // ระบบนิเวศและสิ่งแวดล้อม
    { en: 'ecosystem', th: 'ระบบนิเวศ' },
    { en: 'biodiversity', th: 'ความหลากหลายทางชีวภาพ' },
    { en: 'habitat', th: 'ที่อยู่อาศัย' },
    { en: 'conservation', th: 'การอนุรักษ์' },
    { en: 'sustainability', th: 'ความยั่งยืน' },
    { en: 'pollution', th: 'มลพิษ' },
    { en: 'deforestation', th: 'การตัดไม้ทำลายป่า' },
    { en: 'extinction', th: 'การสูญพันธุ์' },
    { en: 'endangered', th: 'ใกล้สูญพันธุ์' },
    { en: 'predator', th: 'ผู้ล่า' },
    { en: 'prey', th: 'เหยื่อ' },
    { en: 'parasite', th: 'ปรสิต' },
    { en: 'symbiosis', th: 'การพึ่งพาอาศัยกัน' },
    { en: 'biome', th: 'ไบโอม' },
    { en: 'ozone', th: 'โอโซน' },

    // วัฒนธรรมและความบันเทิง
    { en: 'concert', th: 'คอนเสิร์ต' },
    { en: 'theater', th: 'โรงละคร' },
    { en: 'comedy', th: 'ตลก' },
    { en: 'drama', th: 'ละคร' },
    { en: 'thriller', th: 'เขย่าขวัญ' },
    { en: 'horror', th: 'สยองขวัญ' },
    { en: 'romance', th: 'โรแมนติก' },
    { en: 'action', th: 'แอคชั่น' },
    { en: 'sci-fi', th: 'วิทยาศาสตร์' },
    { en: 'fantasy', th: 'แฟนตาซี' },
    { en: 'novel', th: 'นิยาย' },
    { en: 'poem', th: 'บทกวี' },
    { en: 'lyrics', th: 'เนื้อเพลง' },
    { en: 'melody', th: 'ทำนอง' },
    { en: 'rhythm', th: 'จังหวะ' },

    // ทัศนคติและคุณลักษณะบุคลิกภาพ
    { en: 'courage', th: 'ความกล้าหาญ' },
    { en: 'wisdom', th: 'ปัญญา' },
    { en: 'patience', th: 'ความอดทน' },
    { en: 'honesty', th: 'ความซื่อสัตย์' },
    { en: 'loyalty', th: 'ความภักดี' },
    { en: 'optimism', th: 'การมองโลกในแง่ดี' },
    { en: 'pessimism', th: 'การมองโลกในแง่ร้าย' },
    { en: 'humility', th: 'ความถ่อมตน' },
    { en: 'arrogance', th: 'ความหยิ่งยโส' },
    { en: 'kindness', th: 'ความเมตตา' },
    { en: 'cruelty', th: 'ความโหดร้าย' },
    { en: 'generosity', th: 'ความใจกว้าง' },
    { en: 'selfishness', th: 'ความเห็นแก่ตัว' },
    { en: 'intelligence', th: 'ความฉลาด' },
    { en: 'charisma', th: 'เสน่ห์' },

    // ภาษาและการสื่อสาร
    { en: 'dialect', th: 'ภาษาถิ่น' },
    { en: 'accent', th: 'สำเนียง' },
    { en: 'vocabulary', th: 'คำศัพท์' },
    { en: 'grammar', th: 'ไวยากรณ์' },
    { en: 'pronunciation', th: 'การออกเสียง' },
    { en: 'fluency', th: 'ความคล่องแคล่ว' },
    { en: 'bilingual', th: 'สองภาษา' },
    { en: 'multilingual', th: 'หลายภาษา' },
    { en: 'slang', th: 'คำสแลง' },
    { en: 'idiom', th: 'สำนวน' },
    { en: 'metaphor', th: 'การเปรียบเทียบ' },
    { en: 'synonym', th: 'คำพ้องความหมาย' },
    { en: 'antonym', th: 'คำตรงข้าม' },
    { en: 'interpretation', th: 'การตีความ' },
    { en: 'translation', th: 'การแปล' },

    // อาวุธและการป้องกัน
    { en: 'sword', th: 'ดาบ' },
    { en: 'arrow', th: 'ลูกธนู' },
    { en: 'bow', th: 'ธนู' },
    { en: 'shield', th: 'โล่' },
    { en: 'spear', th: 'หอก' },
    { en: 'dagger', th: 'กริช' },
    { en: 'axe', th: 'ขวาน' },
    { en: 'armor', th: 'เกราะ' },
    { en: 'helmet', th: 'หมวกเกราะ' },
    { en: 'cannon', th: 'ปืนใหญ่' },
    { en: 'firearm', th: 'อาวุธปืน' },
    { en: 'bullet', th: 'กระสุน' },
    { en: 'missile', th: 'ขีปนาวุธ' },
    { en: 'fortress', th: 'ป้อมปราการ' },
    { en: 'barricade', th: 'เครื่องกีดขวาง' },

    // กิจกรรมทางปัญญา
    { en: 'problem', th: 'ปัญหา' },
    { en: 'solution', th: 'ทางแก้' },
    { en: 'conclusion', th: 'บทสรุป' },
    { en: 'research', th: 'การวิจัย' },
    { en: 'discovery', th: 'การค้นพบ' },
    { en: 'experiment', th: 'การทดลอง' },
    { en: 'hypothesis', th: 'สมมติฐาน' },
    { en: 'theory', th: 'ทฤษฎี' },
    { en: 'concept', th: 'แนวคิด' },
    { en: 'creativity', th: 'ความคิดสร้างสรรค์' },
    { en: 'invention', th: 'การประดิษฐ์' },
    { en: 'innovation', th: 'นวัตกรรม' },
    { en: 'calculation', th: 'การคำนวณ' },
    { en: 'debate', th: 'การโต้วาที' },
    { en: 'logic', th: 'ตรรกะ' },

    // สถานที่ในเมือง
    { en: 'skyscraper', th: 'ตึกระฟ้า' },
    { en: 'alley', th: 'ซอย' },
    { en: 'boulevard', th: 'ถนนใหญ่' },
    { en: 'intersection', th: 'ทางแยก' },
    { en: 'subway', th: 'รถไฟใต้ดิน' },
    { en: 'pedestrian', th: 'คนเดินเท้า' },
    { en: 'sidewalk', th: 'ทางเท้า' },
    { en: 'plaza', th: 'พลาซ่า' },
    { en: 'fountain', th: 'น้ำพุ' },
    { en: 'monument', th: 'อนุสาวรีย์' },
    { en: 'courthouse', th: 'ศาล' },
    { en: 'prison', th: 'คุก' },
    { en: 'cathedral', th: 'มหาวิหาร' },
    { en: 'mosque', th: 'มัสยิด' },
    { en: 'synagogue', th: 'ศาลาธรรม' },

    // อุตสาหกรรมและการผลิต
    { en: 'factory', th: 'โรงงาน' },
    { en: 'manufacture', th: 'การผลิต' },
    { en: 'assembly', th: 'การประกอบ' },
    { en: 'sculpture', th: 'ประติมากรรม' },
    { en: 'pottery', th: 'เครื่องปั้นดินเผา' },
    { en: 'origami', th: 'ศิลปะพับกระดาษ' },
    { en: 'calligraphy', th: 'การคัดลายมือ' },
    { en: 'embroidery', th: 'งานปัก' },
    { en: 'sketch', th: 'ภาพร่าง' },
    { en: 'mural', th: 'ภาพฝาผนัง' },
    { en: 'collage', th: 'ศิลปะปะติด' },
    { en: 'weaving', th: 'การทอผ้า' },
    { en: 'craft', th: 'งานฝีมือ' },
    { en: 'mosaic', th: 'โมเสก' },
    { en: 'carving', th: 'การแกะสลัก' },
    { en: 'graffiti', th: 'ภาพวาดบนกำแพง' },
    { en: 'portrait', th: 'ภาพเหมือน' },
    { en: 'landscape', th: 'ภาพวิวทิวทัศน์' },

    // แร่ธาตุและอัญมณี
    { en: 'diamond', th: 'เพชร' },
    { en: 'ruby', th: 'ทับทิม' },
    { en: 'sapphire', th: 'ไพลิน' },
    { en: 'emerald', th: 'มรกต' },
    { en: 'jade', th: 'หยก' },
    { en: 'pearl', th: 'ไข่มุก' },
    { en: 'amethyst', th: 'อเมทิสต์' },
    { en: 'topaz', th: 'โทแพซ' },
    { en: 'opal', th: 'โอปอล' },
    { en: 'quartz', th: 'ควอตซ์' },
    { en: 'turquoise', th: 'เทอร์ควอยซ์' },
    { en: 'garnet', th: 'การ์เนต' },
    { en: 'crystal', th: 'คริสตัล' },
    { en: 'mineral', th: 'แร่ธาตุ' },
    { en: 'gemstone', th: 'อัญมณี' },

    // เทศกาลและประเพณี
    { en: 'festival', th: 'เทศกาล' },
    { en: 'carnival', th: 'งานรื่นเริง' },
    { en: 'parade', th: 'ขบวนแห่' },
    { en: 'ritual', th: 'พิธีกรรม' },
    { en: 'ceremony', th: 'พิธี' },
    { en: 'celebration', th: 'การฉลอง' },
    { en: 'tradition', th: 'ประเพณี' },
    { en: 'anniversary', th: 'วันครบรอบ' },
    { en: 'custom', th: 'ธรรมเนียม' },
    { en: 'wedding', th: 'งานแต่งงาน' },
    { en: 'funeral', th: 'งานศพ' },
    { en: 'graduation', th: 'พิธีจบการศึกษา' },
    { en: 'baptism', th: 'พิธีล้างบาป' },
    { en: 'pilgrimage', th: 'การแสวงบุญ' },
    { en: 'procession', th: 'ขบวนแห่' },

    // รูปทรงเรขาคณิต
    { en: 'triangle', th: 'สามเหลี่ยม' },
    { en: 'square', th: 'สี่เหลี่ยมจตุรัส' },
    { en: 'circle', th: 'วงกลม' },
    { en: 'rectangle', th: 'สี่เหลี่ยมผืนผ้า' },
    { en: 'hexagon', th: 'หกเหลี่ยม' },
    { en: 'pentagon', th: 'ห้าเหลี่ยม' },
    { en: 'octagon', th: 'แปดเหลี่ยม' },
    { en: 'cylinder', th: 'ทรงกระบอก' },
    { en: 'sphere', th: 'ทรงกลม' },
    { en: 'cone', th: 'ทรงกรวย' },
    { en: 'cube', th: 'ลูกบาศก์' },
    { en: 'pyramid', th: 'พีระมิด' },
    { en: 'prism', th: 'ปริซึม' },
    { en: 'diagonal', th: 'แนวทแยง' },
    { en: 'parallel', th: 'ขนาน' },

    // สถาปัตยกรรมและการก่อสร้าง
    { en: 'skyscraper', th: 'ตึกระฟ้า' },
    { en: 'arch', th: 'โค้ง' },
    { en: 'column', th: 'เสา' },
    { en: 'dome', th: 'โดม' },
    { en: 'foundation', th: 'ฐานราก' },
    { en: 'beam', th: 'คาน' },
    { en: 'facade', th: 'ด้านหน้าอาคาร' },
    { en: 'balcony', th: 'ระเบียง' },
    { en: 'terrace', th: 'ดาดฟ้า' },
    { en: 'mansion', th: 'คฤหาสน์' },
    { en: 'cottage', th: 'กระท่อม' },
    { en: 'hut', th: 'กระต๊อบ' },
    { en: 'staircase', th: 'บันไดเวียน' },
    { en: 'blueprint', th: 'แบบแปลน' },
    { en: 'scaffold', th: 'นั่งร้าน' },

    // สิ่งเหนือธรรมชาติและเทพนิยาย
    { en: 'fairy', th: 'นางฟ้า' },
    { en: 'wizard', th: 'พ่อมด' },
    { en: 'witch', th: 'แม่มด' },
    { en: 'dragon', th: 'มังกร' },
    { en: 'unicorn', th: 'ยูนิคอร์น' },
    { en: 'elf', th: 'เอลฟ์' },
    { en: 'goblin', th: 'ก็อบลิน' },
    { en: 'dwarf', th: 'คนแคระ' },
    { en: 'mermaid', th: 'นางเงือก' },
    { en: 'ghost', th: 'ผี' },
    { en: 'vampire', th: 'แวมไพร์' },
    { en: 'werewolf', th: 'มนุษย์หมาป่า' },
    { en: 'zombie', th: 'ซอมบี้' },
    { en: 'demon', th: 'ปีศาจ' },
    { en: 'angel', th: 'เทวดา' },

    // การเดินทางและการท่องเที่ยว
    { en: 'journey', th: 'การเดินทาง' },
    { en: 'voyage', th: 'การเดินเรือ' },
    { en: 'expedition', th: 'การเดินทางสำรวจ' },
    { en: 'adventure', th: 'การผจญภัย' },
    { en: 'tour', th: 'ทัวร์' },
    { en: 'itinerary', th: 'กำหนดการเดินทาง' },
    { en: 'destination', th: 'จุดหมายปลายทาง' },
    { en: 'souvenir', th: 'ของที่ระลึก' },
    { en: 'luggage', th: 'สัมภาระ' },
    { en: 'passport', th: 'หนังสือเดินทาง' },
    { en: 'visa', th: 'วีซ่า' },
    { en: 'customs', th: 'ศุลกากร' },
    { en: 'immigration', th: 'ตรวจคนเข้าเมือง' },
    { en: 'resort', th: 'รีสอร์ท' },
    { en: 'cabin', th: 'กระท่อมพักแรม' },

    // ดิจิทัลและเกม
    { en: 'console', th: 'เครื่องเกม' },
    { en: 'controller', th: 'ตัวควบคุมเกม' },
    { en: 'quest', th: 'ภารกิจ' },
    { en: 'arcade', th: 'ตู้เกมหยอดเหรียญ' },
    { en: 'avatar', th: 'ตัวละครในเกม' },
    { en: 'level', th: 'ระดับ' },
    { en: 'score', th: 'คะแนน' },
    { en: 'highscore', th: 'คะแนนสูงสุด' },
    { en: 'achievement', th: 'ความสำเร็จในเกม' },
    { en: 'checkpoint', th: 'จุดบันทึก' },
    { en: 'puzzle', th: 'ปริศนา' },
    { en: 'strategy', th: 'กลยุทธ์' },
    { en: 'simulation', th: 'การจำลอง' },
    { en: 'programmer', th: 'โปรแกรมเมอร์' },
    { en: 'developer', th: 'นักพัฒนา' },

    // รสชาติและประสบการณ์ทางประสาทสัมผัส
    { en: 'flavor', th: 'รสชาติ' },
    { en: 'aroma', th: 'กลิ่นหอม' },
    { en: 'texture', th: 'เนื้อสัมผัส' },
    { en: 'fragrance', th: 'กลิ่นหอม' },
    { en: 'scent', th: 'กลิ่น' },
    { en: 'stench', th: 'กลิ่นเหม็น' },
    { en: 'silky', th: 'เนียนนุ่มดุจไหม' },
    { en: 'rough', th: 'หยาบ' },
    { en: 'smooth', th: 'เรียบ' },
    { en: 'fuzzy', th: 'ฟู' },
    { en: 'crunchy', th: 'กรอบ' },
    { en: 'creamy', th: 'ครีมมี่' },
    { en: 'juicy', th: 'ฉ่ำน้ำ' },
    { en: 'tangy', th: 'เปรี้ยวฉุน' },
    { en: 'pungent', th: 'ฉุน' },

    // กฎหมายและระบบยุติธรรม
    { en: 'court', th: 'ศาล' },
    { en: 'verdict', th: 'คำตัดสิน' },
    { en: 'testimony', th: 'คำให้การ' },
    { en: 'witness', th: 'พยาน' },
    { en: 'evidence', th: 'หลักฐาน' },
    { en: 'punishment', th: 'การลงโทษ' },
    { en: 'defense', th: 'การป้องกัน' },
    { en: 'prosecution', th: 'การฟ้องร้อง' },
    { en: 'crime', th: 'อาชญากรรม' },
    { en: 'lawsuit', th: 'คดีความ' },
    { en: 'legality', th: 'ความชอบด้วยกฎหมาย' },
    { en: 'plaintiff', th: 'โจทก์' },
    { en: 'defendant', th: 'จำเลย' },
    { en: 'bail', th: 'การประกันตัว' },
    { en: 'jurisdiction', th: 'เขตอำนาจศาล' },

    // กีฬาและการแข่งขัน (เพิ่มเติม)
    { en: 'medal', th: 'เหรียญรางวัล' },
    { en: 'trophy', th: 'ถ้วยรางวัล' },
    { en: 'champion', th: 'แชมเปี้ยน' },
    { en: 'tournament', th: 'ทัวร์นาเมนต์' },
    { en: 'league', th: 'ลีก' },
    { en: 'referee', th: 'ผู้ตัดสิน' },
    { en: 'coach', th: 'ผู้ฝึกสอน' },
    { en: 'athlete', th: 'นักกีฬา' },
    { en: 'marathon', th: 'มาราธอน' },
    { en: 'triathlon', th: 'ไตรกีฬา' },
    { en: 'badminton', th: 'แบดมินตัน' },
    { en: 'rugby', th: 'รักบี้' },
    { en: 'wrestling', th: 'มวยปล้ำ' },
    { en: 'fencing', th: 'ดาบสากล' },
    { en: 'gymnastics', th: 'ยิมนาสติก' },

    // ระบบนิเวศและสิ่งแวดล้อม
    { en: 'ecosystem', th: 'ระบบนิเวศ' },
    { en: 'biodiversity', th: 'ความหลากหลายทางชีวภาพ' },
    { en: 'habitat', th: 'ที่อยู่อาศัย' },
    { en: 'conservation', th: 'การอนุรักษ์' },
    { en: 'sustainability', th: 'ความยั่งยืน' },
    { en: 'pollution', th: 'มลพิษ' },
    { en: 'deforestation', th: 'การตัดไม้ทำลายป่า' },
    { en: 'extinction', th: 'การสูญพันธุ์' },
    { en: 'endangered', th: 'ใกล้สูญพันธุ์' },
    { en: 'predator', th: 'ผู้ล่า' },
    { en: 'prey', th: 'เหยื่อ' },
    { en: 'parasite', th: 'ปรสิต' },
    { en: 'symbiosis', th: 'การพึ่งพาอาศัยกัน' },
    { en: 'biome', th: 'ไบโอม' },
    { en: 'ozone', th: 'โอโซน' },

    // วัฒนธรรมและความบันเทิง
    { en: 'concert', th: 'คอนเสิร์ต' },
    { en: 'theater', th: 'โรงละคร' },
    { en: 'comedy', th: 'ตลก' },
    { en: 'drama', th: 'ละคร' },
    { en: 'thriller', th: 'เขย่าขวัญ' },
    { en: 'horror', th: 'สยองขวัญ' },
    { en: 'romance', th: 'โรแมนติก' },
    { en: 'action', th: 'แอคชั่น' },
    { en: 'sci-fi', th: 'วิทยาศาสตร์' },
    { en: 'fantasy', th: 'แฟนตาซี' },
    { en: 'novel', th: 'นิยาย' },
    { en: 'poem', th: 'บทกวี' },
    { en: 'lyrics', th: 'เนื้อเพลง' },
    { en: 'melody', th: 'ทำนอง' },
    { en: 'rhythm', th: 'จังหวะ' },

    // ทัศนคติและคุณลักษณะบุคลิกภาพ
    { en: 'courage', th: 'ความกล้าหาญ' },
    { en: 'wisdom', th: 'ปัญญา' },
    { en: 'patience', th: 'ความอดทน' },
    { en: 'honesty', th: 'ความซื่อสัตย์' },
    { en: 'loyalty', th: 'ความภักดี' },
    { en: 'optimism', th: 'การมองโลกในแง่ดี' },
    { en: 'pessimism', th: 'การมองโลกในแง่ร้าย' },
    { en: 'humility', th: 'ความถ่อมตน' },
    { en: 'arrogance', th: 'ความหยิ่งยโส' },
    { en: 'kindness', th: 'ความเมตตา' },
    { en: 'cruelty', th: 'ความโหดร้าย' },
    { en: 'generosity', th: 'ความใจกว้าง' },
    { en: 'selfishness', th: 'ความเห็นแก่ตัว' },
    { en: 'intelligence', th: 'ความฉลาด' },
    { en: 'charisma', th: 'เสน่ห์' },

    // ภาษาและการสื่อสาร
    { en: 'dialect', th: 'ภาษาถิ่น' },
    { en: 'accent', th: 'สำเนียง' },
    { en: 'vocabulary', th: 'คำศัพท์' },
    { en: 'grammar', th: 'ไวยากรณ์' },
    { en: 'pronunciation', th: 'การออกเสียง' },
    { en: 'fluency', th: 'ความคล่องแคล่ว' },
    { en: 'bilingual', th: 'สองภาษา' },
    { en: 'multilingual', th: 'หลายภาษา' },
    { en: 'slang', th: 'คำสแลง' },
    { en: 'idiom', th: 'สำนวน' },
    { en: 'metaphor', th: 'การเปรียบเทียบ' },
    { en: 'synonym', th: 'คำพ้องความหมาย' },
    { en: 'antonym', th: 'คำตรงข้าม' },
    { en: 'interpretation', th: 'การตีความ' },
    { en: 'translation', th: 'การแปล' },

    // อาวุธและการป้องกัน
    { en: 'sword', th: 'ดาบ' },
    { en: 'arrow', th: 'ลูกธนู' },
    { en: 'bow', th: 'ธนู' },
    { en: 'shield', th: 'โล่' },
    { en: 'spear', th: 'หอก' },
    { en: 'dagger', th: 'กริช' },
    { en: 'axe', th: 'ขวาน' },
    { en: 'armor', th: 'เกราะ' },
    { en: 'helmet', th: 'หมวกเกราะ' },
    { en: 'cannon', th: 'ปืนใหญ่' },
    { en: 'firearm', th: 'อาวุธปืน' },
    { en: 'bullet', th: 'กระสุน' },
    { en: 'missile', th: 'ขีปนาวุธ' },
    { en: 'fortress', th: 'ป้อมปราการ' },
    { en: 'barricade', th: 'เครื่องกีดขวาง' },

    // กิจกรรมทางปัญญา
    { en: 'problem', th: 'ปัญหา' },
    { en: 'solution', th: 'ทางแก้' },
    { en: 'conclusion', th: 'บทสรุป' },
    { en: 'research', th: 'การวิจัย' },
    { en: 'discovery', th: 'การค้นพบ' },
    { en: 'experiment', th: 'การทดลอง' },
    { en: 'hypothesis', th: 'สมมติฐาน' },
    { en: 'theory', th: 'ทฤษฎี' },
    { en: 'concept', th: 'แนวคิด' },
    { en: 'creativity', th: 'ความคิดสร้างสรรค์' },
    { en: 'invention', th: 'การประดิษฐ์' },
    { en: 'innovation', th: 'นวัตกรรม' },
    { en: 'calculation', th: 'การคำนวณ' },
    { en: 'debate', th: 'การโต้วาที' },
    { en: 'logic', th: 'ตรรกะ' },

    // สถานที่ในเมือง
    { en: 'skyscraper', th: 'ตึกระฟ้า' },
    { en: 'alley', th: 'ซอย' },
    { en: 'boulevard', th: 'ถนนใหญ่' },
    { en: 'intersection', th: 'ทางแยก' },
    { en: 'subway', th: 'รถไฟใต้ดิน' },
    { en: 'pedestrian', th: 'คนเดินเท้า' },
    { en: 'sidewalk', th: 'ทางเท้า' },
    { en: 'plaza', th: 'พลาซ่า' },
    { en: 'fountain', th: 'น้ำพุ' },
    { en: 'monument', th: 'อนุสาวรีย์' },
    { en: 'courthouse', th: 'ศาล' },
    { en: 'prison', th: 'คุก' },
    { en: 'cathedral', th: 'มหาวิหาร' },
    { en: 'mosque', th: 'มัสยิด' },
    { en: 'synagogue', th: 'ศาลาธรรม' },

    // อุตสาหกรรมและการผลิต
    { en: 'factory', th: 'โรงงาน' },
    { en: 'manufacture', th: 'การผลิต' },
    { en: 'assembly', th: 'การประกอบ' }
  ];
};

export const getRandomVocabulary = () => {
  const vocabList = vocabularyList();

  // Create a unique list to ensure we don't have duplicates
  const uniqueVocabMap = new Map();
  vocabList.forEach(item => {
    // Only keep the first occurrence of each English word
    if (!uniqueVocabMap.has(item.en.toLowerCase())) {
      uniqueVocabMap.set(item.en.toLowerCase(), item);
    }
  });

  // Convert map back to array for random selection
  const uniqueVocabList = Array.from(uniqueVocabMap.values());

  // Get a random index using proper randomization
  const randomIndex = Math.floor(Math.random() * uniqueVocabList.length);

  console.log(`Selected index: ${randomIndex}, word: ${uniqueVocabList[randomIndex].en}`);
  return uniqueVocabList[randomIndex];
};
